### ISSUE TITLE
How PE file is mapped to memory

### ISSUE THREAD

**Issue by Jasemalsadi** [EgeBalci/MapPE#1]
I just want to ask if you would know an article or book that illustrate how the PE file is mapped to memory ?

**Comment by EgeBalci** [comment]
Check these,

- https://www.youtube.com/watch?v=cc1tX1t_bLg
- https://www.youtube.com/watch?v=l6GjU8fm8sM
- https://blog.kowalczyk.info/articles/pefileformat.html
- http://darkblue.ch/programming/PE%20File%20Structure.pdf
- https://docs.microsoft.com/en-us/windows/desktop/debug/pe-format

**Comment by Jasemalsadi** [comment]
Great resources, Thank you.
